[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bot2h"
version = "0.1"
requires-python = ">= 3.9"
description = "Interface to http2irc"
dependencies = ["aiohttp"]

